// Code generated by go-simpler.org/sloggen. DO NOT EDIT.

package example

import "context"
import "fmt"
import "log/slog"
import "runtime"
import "strings"
import "time"

const LevelTrace = slog.Level(-8)
const LevelDebug = slog.Level(-4)
const LevelInfo = slog.Level(0)
const LevelWarn = slog.Level(4)
const LevelError = slog.Level(8)

const RequestId = "request_id"

func CreatedAt(value time.Time) slog.Attr { return slog.Time("created_at", value) }
func Err(value error) slog.Attr           { return slog.Any("err", value) }
func UserId(value int) slog.Attr          { return slog.Int("user_id", value) }

func ParseLevel(s string) (slog.Level, error) {
	switch strings.ToUpper(s) {
	case "TRACE":
		return LevelTrace, nil
	case "DEBUG":
		return LevelDebug, nil
	case "INFO":
		return LevelInfo, nil
	case "WARN":
		return LevelWarn, nil
	case "ERROR":
		return LevelError, nil
	default:
		return 0, fmt.Errorf("slog: level string %q: unknown name", s)
	}
}

func ReplaceAttr(_ []string, attr slog.Attr) slog.Attr {
	if attr.Key != slog.LevelKey {
		return attr
	}
	switch attr.Value.Any().(slog.Level) {
	case LevelTrace:
		attr.Value = slog.StringValue("TRACE")
	case LevelDebug:
		attr.Value = slog.StringValue("DEBUG")
	case LevelInfo:
		attr.Value = slog.StringValue("INFO")
	case LevelWarn:
		attr.Value = slog.StringValue("WARN")
	case LevelError:
		attr.Value = slog.StringValue("ERROR")
	}
	return attr
}

type Logger struct{ handler slog.Handler }

func New(h slog.Handler) *Logger { return &Logger{handler: h} }

func (l *Logger) Handler() slog.Handler { return l.handler }

func (l *Logger) Enabled(ctx context.Context, level slog.Level) bool {
	return l.handler.Enabled(ctx, level)
}

func (l *Logger) With(attrs ...slog.Attr) *Logger {
	if len(attrs) == 0 {
		return l
	}
	return &Logger{handler: l.handler.WithAttrs(attrs)}
}

func (l *Logger) WithGroup(name string) *Logger {
	if name == "" {
		return l
	}
	return &Logger{handler: l.handler.WithGroup(name)}
}

func (l *Logger) Log(ctx context.Context, level slog.Level, msg string, attrs ...slog.Attr) {
	l.log(ctx, level, msg, attrs)
}

func (l *Logger) Trace(ctx context.Context, msg string, attrs ...slog.Attr) {
	l.log(ctx, LevelTrace, msg, attrs)
}

func (l *Logger) Debug(ctx context.Context, msg string, attrs ...slog.Attr) {
	l.log(ctx, LevelDebug, msg, attrs)
}

func (l *Logger) Info(ctx context.Context, msg string, attrs ...slog.Attr) {
	l.log(ctx, LevelInfo, msg, attrs)
}

func (l *Logger) Warn(ctx context.Context, msg string, attrs ...slog.Attr) {
	l.log(ctx, LevelWarn, msg, attrs)
}

func (l *Logger) Error(ctx context.Context, msg string, attrs ...slog.Attr) {
	l.log(ctx, LevelError, msg, attrs)
}

func (l *Logger) log(ctx context.Context, level slog.Level, msg string, attrs []slog.Attr) {
	if !l.handler.Enabled(ctx, level) {
		return
	}
	var pcs [1]uintptr
	runtime.Callers(3, pcs[:])
	r := slog.NewRecord(time.Now(), level, msg, pcs[0])
	r.AddAttrs(attrs...)
	_ = l.handler.Handle(ctx, r)
}
