// Code generated by go-simpler.org/slog-gen. DO NOT EDIT.

package example

import "fmt"
import "log/slog"
import "strings"
import "time"

const LevelTrace = slog.Level(-8)
const LevelDebug = slog.Level(-4)
const LevelInfo = slog.Level(0)
const LevelWarn = slog.Level(4)
const LevelError = slog.Level(8)

const RequestId = "request_id"

func CreatedAt(value time.Time) slog.Attr {
	return slog.Time("created_at", value)
}

func Err(value error) slog.Attr {
	return slog.Any("err", value)
}

func UserId(value int) slog.Attr {
	return slog.Int("user_id", value)
}

func ParseLevel(s string) (slog.Level, error) {
	switch strings.ToUpper(s) {
	case "TRACE":
		return LevelTrace, nil
	case "DEBUG":
		return LevelDebug, nil
	case "INFO":
		return LevelInfo, nil
	case "WARN":
		return LevelWarn, nil
	case "ERROR":
		return LevelError, nil
	default:
		return 0, fmt.Errorf("slog: level string %q: unknown name", s)
	}
}

func ReplaceAttr(_ []string, attr slog.Attr) slog.Attr {
	if attr.Key != slog.LevelKey {
		return attr
	}
	switch attr.Value.Any().(slog.Level) {
	case LevelTrace:
		attr.Value = slog.StringValue("TRACE")
	case LevelDebug:
		attr.Value = slog.StringValue("DEBUG")
	case LevelInfo:
		attr.Value = slog.StringValue("INFO")
	case LevelWarn:
		attr.Value = slog.StringValue("WARN")
	case LevelError:
		attr.Value = slog.StringValue("ERROR")
	}
	return attr
}
