package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func run() error {
	var pkgName string
	attrs := make(map[string]string) // name:type

	fs := flag.NewFlagSet("slog-gen", flag.ContinueOnError)
	fs.StringVar(&pkgName, "pkg", "slogattr", "the name for the generated package")
	fs.Func("attr", "add a constructor for <name:type> (e.g. -attr=user_id:int)", func(s string) error {
		parts := strings.Split(s, ":")
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return errors.New("invalid format")
		}
		attrs[parts[0]] = parts[1]
		return nil
	})
	if err := fs.Parse(os.Args[1:]); err != nil {
		return fmt.Errorf("parsing flags: %w", err)
	}

	imports := []string{"log/slog"}
	for _, typeName := range attrs {
		if strings.HasPrefix(typeName, "time.") {
			imports = append(imports, "time")
			break
		}
	}

	// TODO: replace with text/template?
	var buf bytes.Buffer
	write := func(format string, args ...any) {
		_, _ = fmt.Fprintf(&buf, format+"\n", args...)
	}

	write("// Code generated by go-simpler.org/slog-gen. DO NOT EDIT.\n")
	write("package %s\n", pkgName)
	for _, imp := range imports {
		write(`import "%s"`, imp)
	}

	for attrName, typeName := range attrs {
		funcName := strings.Title(strings.TrimPrefix(typeName, "time."))
		if _, builtin := map[string]struct{}{
			"String":   {},
			"Int64":    {},
			"Int":      {},
			"Uint64":   {},
			"Float64":  {},
			"Bool":     {},
			"Time":     {},
			"Duration": {},
		}[funcName]; !builtin {
			funcName = "Any"
		}

		write(`
func %s(value %s) slog.Attr {
	return slog.%s("%s", value)
}`, snakeToCamel(attrName), typeName, funcName, attrName)
	}

	if err := os.Mkdir(pkgName, 0755); err != nil && !errors.Is(err, os.ErrExist) {
		return fmt.Errorf("mkdir %s: %w", pkgName, err)
	}
	if err := os.WriteFile(pkgName+"/attr.go", buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("writing file: %w", err)
	}

	return nil
}

func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		parts[i] = strings.Title(parts[i])
	}
	return strings.Join(parts, "")
}
